import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
//seo ko lagi or search garda yo page aaune banauna ko lagi
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* below was css body or tailwind css */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       ><Navbar />
        {/* here we can place the navbar */}
        {/* below was the body part which is display dynamically as routing */}
        {children}

        {/* here we can place the footer */}
      </body>
    </html>
  );
}
